name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]   # change if your default branch is 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get   # ensures packages are fetched before build

      - name: Build Flutter Web
        run: flutter build web --wasm --base-href "/portfolio/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
